### ISSUE TITLE
Eco plugins error

### ISSUE THREAD

**Issue by devbaraus** [zorbeytorunoglu/thebestranks#2]
For some reason it isn't working with eco plugins.

**Comment by devbaraus** [comment]
The whole family of plugins doesn't work...
An example is this one: https://www.spigotmc.org/resources/ecoskills-%E2%AD%95-addictive-mmorpg-progression-%E2%9C%85-create-custom-effects-%E2%9C%A8-levelling-stats.95541/

**Comment by devbaraus** [comment]
A guy of their support asked the your .jar (right) and send the another (left).

![image](https://user-images.githubusercontent.com/43019623/194779183-571be587-d867-4b28-b75e-9e66185267c2.png)

**Comment by zorbeytorunoglu** [comment]
I'm aware of that. Eco plugins doesn't want other plugins to use dependencies like "Kotlin" and if they do, it asks people to remove those plugins otherwise it disables itself. The support staff, the one who helped you, basically removed Kotlin dependency from the project to solve this problem.

It should work fine now.
